/**
 * Generates `preset.cjs` from `src/index.ts`, so the Tailwind theme and the
 * TypeScript tokens can never drift apart. One preset, both platforms: metro
 * (NativeWind) and Next.js (react-native-web) load the same file.
 *
 * Run by `pnpm --filter @kanon/tokens build`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(join(here, '..', 'src', 'index.ts'), 'utf8');

/** Pulls `key: 'value',` pairs out of a named `export const X = { ... } as const`. */
function block(name) {
  const start = src.indexOf(`export const ${name} = {`);
  if (start === -1) throw new Error(`missing export: ${name}`);
  const end = src.indexOf('} as const;', start);
  const body = src.slice(start, end);
  const out = [];
  for (const m of body.matchAll(/^\s*'?([A-Za-z0-9_-]+)'?:\s*'([^']+)',/gm)) {
    out.push([m[1], m[2]]);
  }
  if (out.length === 0) throw new Error(`empty export: ${name}`);
  return out;
}

const device = /export const device = \{\s*width: (\d+),\s*height: (\d+),/.exec(src);
if (!device) throw new Error('missing export: device');

const obj = (pairs) =>
  `{\n${pairs.map(([k, v]) => `    ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n')}\n  }`;

/*
 * Tailwind v4 derives spacing from a single `--spacing` step, so the design can
 * say `py-3.25`. v3 needs the scale written out; NativeWind is a v3 plugin, so
 * it is written out here rather than the design being rounded to fit the tool.
 */
const spacing = [['px', '1px']];
for (let n = 0; n <= 128; n += 0.25) spacing.push([String(n), `${n * 4}px`]);
spacing.push(['device-w', `${device[1]}px`], ['device-h', `${device[2]}px`]);

const mono = Object.fromEntries(block('monoFamilies'));

const out = `/* GENERATED by @kanon/tokens — edit src/index.ts, then \`pnpm --filter @kanon/tokens build\`. */

const colors = ${obj(block('colors')).replace(/^ {2}/gm, '')};

const fontSize = ${obj(block('fontSize')).replace(/^ {2}/gm, '')};

const letterSpacing = ${obj(block('tracking')).replace(/^ {2}/gm, '')};

const spacing = ${obj(spacing).replace(/^ {2}/gm, '')};

const device = { width: ${device[1]}, height: ${device[2]} };

/**
 * The mono face, as three explicit utilities.
 *
 * On the web one family carries every weight. On a device each weight is a
 * separate registered family, and \`fontWeight\` against a custom family is
 * unreliable on Android — so weight is part of the utility, not a modifier.
 */
const WEB_MONO = ['var(--kanon-font-mono)', 'ui-monospace', 'SFMono-Regular', 'monospace'];
const WEB_SANS = ['var(--kanon-font-sans)', 'system-ui', 'Helvetica Neue', 'Arial', 'sans-serif'];

/**
 * @param {{ mono?: { regular: string, medium: string, bold: string }, sans?: string[] }} [options]
 *   Omit for the web. Metro passes the family names registered with expo-font.
 */
module.exports = function kanonPreset(options = {}) {
  const mono = options.mono ?? {
    regular: WEB_MONO.join(', '),
    medium: WEB_MONO.join(', '),
    bold: WEB_MONO.join(', '),
  };
  const sans = options.sans ?? WEB_SANS;

  return {
    theme: {
      extend: {
        colors,
        fontSize,
        letterSpacing,
        spacing,
        minHeight: ({ theme }) => theme('spacing'),
        minWidth: ({ theme }) => theme('spacing'),
        maxWidth: ({ theme }) => theme('spacing'),
        maxHeight: ({ theme }) => theme('spacing'),
        fontFamily: { sans, mono: [mono.regular] },
      },
    },
    plugins: [
      ({ addUtilities }) =>
        addUtilities({
          '.font-mono': { fontFamily: mono.regular, fontWeight: '400' },
          '.font-mono-medium': { fontFamily: mono.medium, fontWeight: '500' },
          '.font-mono-bold': { fontFamily: mono.bold, fontWeight: '700' },
          '.no-scrollbar': {
            scrollbarWidth: 'none',
            '&::-webkit-scrollbar': { display: 'none' },
          },
        }),
    ],
  };
};

/** The families expo-font registers on a device. Metro's config passes these in. */
module.exports.nativeMono = ${JSON.stringify(mono, null, 2)};

module.exports.colors = colors;
module.exports.fontSize = fontSize;
module.exports.letterSpacing = letterSpacing;
module.exports.spacing = spacing;
module.exports.device = device;
`;

writeFileSync(join(here, '..', 'preset.cjs'), out);
console.log(
  `@kanon/tokens → preset.cjs (${block('colors').length} colours, ${spacing.length} spacing steps)`,
);
