// Generates tokens.css from src/index.ts so the Tailwind theme and the
// TypeScript tokens can never drift apart. Run by `pnpm build`.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(join(here, '..', 'src', 'index.ts'), 'utf8');

/** Pulls `key: 'value',` pairs out of a named `export const X = { ... } as const`. */
function block(name) {
  const start = src.indexOf(`export const ${name} = {`);
  if (start === -1) throw new Error(`missing export: ${name}`);
  const end = src.indexOf('} as const;', start);
  const body = src.slice(start, end);
  const out = [];
  for (const m of body.matchAll(/^\s*'?([A-Za-z0-9_-]+)'?:\s*'([^']+)',/gm)) {
    out.push([m[1], m[2]]);
  }
  return out;
}

const lines = [
  '/* GENERATED by @kanon/tokens — edit src/index.ts, then `pnpm --filter @kanon/tokens build`. */',
  '@theme {',
  '  --font-mono: var(--kanon-font-mono, ui-monospace), ui-monospace, SFMono-Regular, monospace;',
  '  --font-sans: var(--kanon-font-sans, system-ui), "Helvetica Neue", Helvetica, Arial, sans-serif;',
  '',
];
for (const [k, v] of block('colors')) lines.push(`  --color-${k}: ${v};`);
lines.push('');
for (const [k, v] of block('fontSize')) lines.push(`  --text-${k}: ${v};`);
lines.push('');
for (const [k, v] of block('tracking')) lines.push(`  --tracking-${k}: ${v};`);
lines.push('');

// The artboard the design is drawn against, as spacing tokens so screens can
// say `w-device-w` instead of carrying the number around.
const device = /export const device = \{\s*width: (\d+),\s*height: (\d+),/.exec(src);
if (!device) throw new Error('missing export: device');
lines.push(`  --spacing-device-w: ${device[1]}px;`);
lines.push(`  --spacing-device-h: ${device[2]}px;`);
lines.push('}', '');

writeFileSync(join(here, '..', 'tokens.css'), lines.join('\n'));
console.log(`@kanon/tokens → tokens.css (${lines.length - 4} tokens)`);
